# Generated by Django 3.2 on 2021-04-17 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hacker',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('college', models.CharField(default='TIET', max_length=100)),
                ('skill_1', models.CharField(default='HTML', max_length=100)),
                ('skill_2', models.CharField(default='CSS', max_length=100)),
                ('skill_3', models.CharField(default='Js', max_length=100)),
            ],
        ),
    ]
