# Generated by Django 3.2 on 2021-04-17 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hacker',
            name='name',
            field=models.CharField(default='abc', max_length=100),
        ),
    ]
