# Generated by Django 3.2 on 2021-04-17 10:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hacker',
            name='college',
        ),
        migrations.RemoveField(
            model_name='hacker',
            name='name',
        ),
        migrations.RemoveField(
            model_name='hacker',
            name='skill_1',
        ),
        migrations.RemoveField(
            model_name='hacker',
            name='skill_2',
        ),
        migrations.RemoveField(
            model_name='hacker',
            name='skill_3',
        ),
    ]
